version: '{build}'
install:
  - git submodule update --init --recursive

  # environment and system dependency
  - ps: Start-FileDownload http://downloads.sourceforge.net/levent/libevent-2.0.22-stable.tar.gz
  - tar xf libevent-2.0.22-stable.tar.gz
  - move libevent-2.0.22-stable event
  - xcopy /E event\WIN32-Code event\include
  
  - ps: Start-FileDownload https://github.com/premake/premake-core/releases/download/v5.0.0-alpha9/premake-5.0.0-alpha9-windows.zip
  - 7z x premake-5.0.0-alpha9-windows.zip
  
  - ps: Start-FileDownload http://downloads.sourceforge.net/freetype/freetype-2.7.tar.bz2
  - tar xf freetype-2.7.tar.bz2
  - move freetype-2.7 freetype
  
  - ps: Start-FileDownload http://downloads.sourceforge.net/project/irrlicht/Irrlicht%20SDK/1.8/1.8.4/irrlicht-1.8.4.zip
  - 7z x irrlicht-1.8.4.zip
  - md irrlicht
  - move irrlicht-1.8.4\source\Irrlicht irrlicht\src
  - move irrlicht-1.8.4\include irrlicht\include
  
  - ps: Start-FileDownload https://www.lua.org/ftp/lua-5.2.4.tar.gz
  - tar xf lua-5.2.4.tar.gz
  - move lua-5.2.4\src lua
  
  - ps: Start-FileDownload https://www.sqlite.org/2016/sqlite-amalgamation-3140200.zip
  - 7z x sqlite-amalgamation-3140200.zip
  - move sqlite-amalgamation-3140200 sqlite3

  # let premake happy
  - xcopy /E premake\* .
  
  # patch irrlicht
  - patch -p1 < irrlicht\irrlicht.patch
  
  # premake
  - premake5 vs2015
  
configuration: Release
build: 
    project: build/ygo.sln
    parallel: true
after_build:
  - ps: move bin\release\ygopro.exe .
artifacts:
  - path: ygopro.exe
    name: ygopro
